### PR TITLE
add no-useless-iife

### PR DESCRIPTION
**Pull request by mifi**
https://github.com/transloadit/api2/pull/4740#discussion_r1263570273

### CODE REVIEW

**Review by aduh95 — APPROVED** [review]

**Comment by mifi** [comment]
shall we release a new version of eslint-config-transloadit with no-useless-iife, wdyt? major/minor?

**Comment by aduh95** [comment]
I think if we're adding a new peer dependency, that's somewhat major because it would break consumers updating to that version.

**Comment by aduh95** [comment]
Can we merge this, and release a new major? Do we want more? Maybe remove the dependency on Jest?

**Comment by mifi** [comment]
eslint-plugin-jest was added in https://github.com/transloadit/eslint-config-transloadit/commit/964841906066364e767027966af7bae1872bcb05 - not sure why. I think we can remove it.

**Comment by mifi** [comment]
@kvz wdyt shall I do a major release of eslint-config-transloadit? I will upgrade all deps too

**Comment by kvz** [comment]
That sounds good. We could check in the consuming repos which rules turned out to be too much to fix them over the years, leading to unanimous disables, and maybe exclude them from the next major? Or at least discuss them?

**Pull request merged**
