### PR TITLE
Upgrades and remove jest

### PR DESCRIPTION
**Pull request by mifi**
I can do a major release after this is merged. Any other things missing?

### CODE REVIEW

**Comment by kvz** [comment]
Can we run a trial `fix` in the content & api repo and see if
- the diff is small/expected
- some warnings are gone during install? yarn used to be quite noisy with complaints just because of `eslint-config-transloadit`

**Comment by mifi** [comment]
Yes we could do that. @aduh95 was there any repo you wanted to test first also since you [requested a major release](https://github.com/transloadit/eslint-config-transloadit/pull/24#issuecomment-1740894832)?

**Comment by mifi** [comment]
I also `yarn remove @babel/core @babel/eslint-parser @babel/eslint-plugin` because I don't know why those are needed (added https://github.com/transloadit/eslint-config-transloadit/commit/78648e8717e6f2920f8a172fb39aa4be70a3889d https://github.com/transloadit/eslint-config-transloadit/commit/bd1bb8a9cf71911c1119afd2060c517a9b2bc2aa)

**Comment by mifi** [comment]
I will try to publish a pre-release version

**Comment by mifi** [comment]
can be installed with `yarn add -D eslint-config-transloadit@next`

**Comment by mifi** [comment]
oops right you need to add that peer depeendency too:
```
yarn add -D eslint-plugin-transloadit
yarn add -D eslint-config-transloadit@next
```

**Comment by kvz** [comment]
Result: https://github.com/transloadit/content/pull/3051

**Pull request merged**
